services:
  # Serviço do Banco de Dados
  db:
    image: mysql:8.0
    container_name: linguados-db
    restart: always
    environment:
      MYSQL_DATABASE: linguados
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d

  # Serviço da Aplicação Java
  app:
    build: .
    container_name: linguados-app
    depends_on:
      - db
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: linguados
      DB_USER: root
      DB_PASSWORD: root
    stdin_open: true
    tty: true

volumes:
  mysql_data: