services:
  # Banco de Dados MySQL
  linguados-db:
    image: mysql:8.0
    container_name: linguados-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: linguados
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - linguados-net

  # Aplicação Web (Tomcat)
  linguados-app:
    build: .
    container_name: linguados-app
    restart: always
    ports:
      - "8080:8080"  # Agora mapeamos a porta do Tomcat
    depends_on:
      - linguados-db
    environment:
      DB_URL: jdbc:mysql://linguados-db:3306/linguados?useSSL=false&allowPublicKeyRetrieval=true
      DB_USER: root
      DB_PASSWORD: root
    networks:
      - linguados-net

networks:
  linguados-net:
    driver: bridge